### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([35, 70, 99, 15, 43, 34, 81, 13, 28, 42, 11, 74, 83, 18, 94])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[58, 73, 57, 44],
       [24, 43, 47, 97],
       [69, 81, 90, 27],
       [ 3,  5, 22, 54],
       [71, 13, 45, 95],
       [41, 48, 18, 84]])

In [5]:
np.sort(a)

array([ 5,  6, 19, 21, 25, 33, 34, 36, 39, 56, 60, 67, 68, 88, 94])

In [6]:
np.sort(a)[::-1]

array([94, 88, 68, 67, 60, 56, 39, 36, 34, 33, 25, 21, 19,  6,  5])

In [8]:
np.sort(b,axis=0)

array([[14,  1,  5, 20],
       [20, 16, 49, 51],
       [34, 40, 52, 65],
       [74, 44, 63, 65],
       [77, 45, 66, 66],
       [99, 91, 78, 90]])

In [9]:
np.sort(b,axis=1)

array([[20, 40, 66, 99],
       [ 5, 20, 45, 90],
       [16, 34, 52, 65],
       [ 1, 14, 63, 65],
       [44, 49, 66, 74],
       [51, 77, 78, 91]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [10]:
a

array([ 6, 33, 36, 88, 68, 19,  5, 60, 56, 21, 25, 34, 39, 94, 67])

In [ ]:
# code
np.append(a,200)

array([ 11,  53,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21, 200])

In [3]:
b

array([[58, 73, 57, 44],
       [24, 43, 47, 97],
       [69, 81, 90, 27],
       [ 3,  5, 22, 54],
       [71, 13, 45, 95],
       [41, 48, 18, 84]])

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[99.        , 40.        , 66.        , 20.        ,  0.9356188 ],
       [20.        , 45.        ,  5.        , 90.        ,  0.38641578],
       [34.        , 16.        , 52.        , 65.        ,  0.41972222],
       [14.        ,  1.        , 63.        , 65.        ,  0.69905004],
       [74.        , 44.        , 49.        , 66.        ,  0.98466163],
       [77.        , 91.        , 78.        , 51.        ,  0.24229617]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [14]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [17]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [18]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [19]:
np.unique(d)

array([ 6,  7,  8,  9, 10, 11])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [26]:
a

array([ 6, 33, 36, 88, 68, 19,  5, 60, 56, 21, 25, 34, 39, 94, 67])

In [27]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 3,  4,  7,  8, 13, 14]),)

In [25]:
np.where(a==60)

(array([7]),)

In [28]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 6, 33, 36,  0,  0, 19,  5,  0,  0, 21, 25, 34, 39,  0,  0])

In [29]:
np.where(a%2 == 0,0,a)

array([ 0, 33,  0,  0,  0, 19,  5,  0,  0, 21, 25,  0, 39,  0, 67])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [30]:
# code
a

array([ 6, 33, 36, 88, 68, 19,  5, 60, 56, 21, 25, 34, 39, 94, 67])

In [32]:
np.argmax(a)

13

In [33]:
b

array([[99, 40, 66, 20],
       [20, 45,  5, 90],
       [34, 16, 52, 65],
       [14,  1, 63, 65],
       [74, 44, 49, 66],
       [77, 91, 78, 51]])

In [34]:
np.argmax(b,axis=0)

array([0, 5, 5, 1])

In [35]:
np.argmax(b,axis=1)

array([0, 3, 3, 3, 0, 1])

In [36]:
# np.argmin
np.argmin(a)

6

In [37]:
np.argmin(b,axis=0)

array([3, 3, 1, 0])

In [38]:
np.argmin(b,axis=1)

array([3, 2, 1, 1, 1, 3])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [41]:
a

array([ 6, 33, 36, 88, 68, 19,  5, 60, 56, 21, 25, 34, 39, 94, 67])

In [42]:
np.cumsum(a)

array([  6,  39,  75, 163, 231, 250, 255, 315, 371, 392, 417, 451, 490,
       584, 651])

In [43]:
b

array([[99, 40, 66, 20],
       [20, 45,  5, 90],
       [34, 16, 52, 65],
       [14,  1, 63, 65],
       [74, 44, 49, 66],
       [77, 91, 78, 51]])

In [44]:
np.cumsum(b,axis=1)

array([[ 99, 139, 205, 225],
       [ 20,  65,  70, 160],
       [ 34,  50, 102, 167],
       [ 14,  15,  78, 143],
       [ 74, 118, 167, 233],
       [ 77, 168, 246, 297]])

In [45]:
np.cumsum(b)

array([  99,  139,  205,  225,  245,  290,  295,  385,  419,  435,  487,
        552,  566,  567,  630,  695,  769,  813,  862,  928, 1005, 1096,
       1174, 1225])

In [46]:
# np.cumprod
np.cumprod(a)

array([                   6,                  198,                 7128,
                     627264,             42653952,            810425088,
                 4052125440,         243127526400,       13615141478400,
            285917971046400,     7147949276160000,   243030275389440000,
       -8968563333521391616,  5505274039628562432,   -81520819077349376])

In [47]:
a

array([ 6, 33, 36, 88, 68, 19,  5, 60, 56, 21, 25, 34, 39, 94, 67])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [51]:
a

array([ 6, 33, 36, 88, 68, 19,  5, 60, 56, 21, 25, 34, 39, 94, 67])

In [49]:
np.percentile(a,50)

36.0

In [52]:
np.percentile(a,75)

63.5

In [50]:
np.median(a)

36.0

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [53]:
# code
a


array([ 6, 33, 36, 88, 68, 19,  5, 60, 56, 21, 25, 34, 39, 94, 67])

In [57]:
np.isin(a,33)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [58]:
a[np.isin(a,33)]

array([33])

In [62]:
a[np.isin(a,[36,5,56,41,39])]

array([36,  5, 56, 39])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [63]:
# code
a

array([ 6, 33, 36, 88, 68, 19,  5, 60, 56, 21, 25, 34, 39, 94, 67])

In [64]:
np.flip(a)

array([67, 94, 39, 34, 25, 21, 56, 60,  5, 19, 68, 88, 36, 33,  6])

In [65]:
b

array([[99, 40, 66, 20],
       [20, 45,  5, 90],
       [34, 16, 52, 65],
       [14,  1, 63, 65],
       [74, 44, 49, 66],
       [77, 91, 78, 51]])

In [66]:
np.flip(b,axis=1)

array([[20, 66, 40, 99],
       [90,  5, 45, 20],
       [65, 52, 16, 34],
       [65, 63,  1, 14],
       [66, 49, 44, 74],
       [51, 78, 91, 77]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [82]:
# code
a

array([110, 530,  36,  88,  68,  19,   5,  60,  56,  21,  25,  34,  39,
        94,  67])

In [83]:
np.put(a,3,100)

In [84]:
a

array([110, 530,  36, 100,  68,  19,   5,  60,  56,  21,  25,  34,  39,
        94,  67])

In [68]:
np.put(a,[0,1],[110,530])

In [69]:
a

array([110, 530,  36,  88,  68,  19,   5,  60,  56,  21,  25,  34,  39,
        94,  67])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. It takes index as an argument.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [70]:
# code
a

array([110, 530,  36,  88,  68,  19,   5,  60,  56,  21,  25,  34,  39,
        94,  67])

In [73]:
np.delete(a,[1])

array([110,  36,  88,  68,  19,   5,  60,  56,  21,  25,  34,  39,  94,
        67])

In [74]:
np.delete(a,[0,2,4])

array([530,  88,  19,   5,  60,  56,  21,  25,  34,  39,  94,  67])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d

In [75]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [76]:
np.intersect1d(m,n)

array([3, 4, 5])

In [77]:
np.setdiff1d(n,m)

array([6, 7])

In [78]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [80]:
# code
a

array([110, 530,  36,  88,  68,  19,   5,  60,  56,  21,  25,  34,  39,
        94,  67])

In [85]:
#numbers less than 25 will be converted into 25 and no. greater than 75 will get converted into 75
np.clip(a,a_min=25,a_max=75)

array([75, 75, 36, 75, 68, 25, 25, 60, 56, 25, 25, 34, 39, 75, 67])