### What is numpy?

Numpy stands for Numerical Python. NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
!pip install numpy

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
type(a)

numpy.ndarray

In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# dtype

In [3]:
a=np.array([1,2,3,4])
a.dtype

dtype('int64')

In [4]:
a=np.array([2.5,7.8,52])
a.dtype

dtype('float64')

In [5]:
a

array([ 2.5,  7.8, 52. ])

In [5]:
a=np.array(["a","b","c"])
a.dtype

dtype('<U1')

In [2]:
a=np.array([1,2,"a",3])
a.dtype

dtype('<U11')

In [3]:
a

array(['1', '2', 'a', '3'], dtype='<U11')

In [6]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

# arange()

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
# with reshape
np.arange(12).reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

# np.ones()

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.ones((4,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# np.zeros() 

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((4,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# np.random.random()

In [16]:
np.random.random(5)

array([0.13096329, 0.56057867, 0.73372902, 0.04949454, 0.58888038])

In [17]:
# np.random
np.random.random((3,4))

array([[0.10063282, 0.86924203, 0.10915509, 0.3714213 ],
       [0.91030317, 0.8638362 , 0.6762136 , 0.87456191],
       [0.3852624 , 0.73403927, 0.3334994 , 0.53407774]])

In [18]:
# np.random
np.random.random((3,3,4))

array([[[0.65631596, 0.43216742, 0.37034844, 0.3185059 ],
        [0.29427683, 0.33503469, 0.86650424, 0.40562951],
        [0.31976218, 0.86267601, 0.1513324 , 0.89498346]],

       [[0.43189143, 0.98577718, 0.77991449, 0.84176518],
        [0.91819862, 0.15175488, 0.1148732 , 0.4500011 ],
        [0.7200643 , 0.33929887, 0.94821454, 0.93009294]],

       [[0.67297511, 0.11491847, 0.15636887, 0.34460613],
        [0.55900107, 0.01935229, 0.81001652, 0.08294356],
        [0.3086523 , 0.07743225, 0.96481724, 0.18982005]]])

# np.random.randint()

In [11]:
np.random.randint(7,size=(10))

array([4, 5, 0, 6, 4, 1, 3, 2, 6, 6])

In [10]:
np.random.randint(7,15,size=(10))

array([14,  9,  9, 13, 14, 11, 12, 13,  8, 10])

In [20]:
np.random.randint(3,size=(2,3))

array([[0, 2, 1],
       [2, 1, 1]])

In [21]:
np.random.randint(3,size=(3,2,3))

array([[[1, 1, 1],
        [1, 2, 0]],

       [[0, 0, 1],
        [2, 1, 0]],

       [[0, 0, 0],
        [1, 0, 0]]])

# np.linspace()

In [23]:
# np.linspace
np.linspace(-10,10,num=10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [24]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

# identity()

In [17]:
# np.identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# random.choice() 

In [27]:
np.random.choice(["pizza","popcorn","taco"],(3,4))

array([['pizza', 'pizza', 'taco', 'popcorn'],
       ['popcorn', 'taco', 'pizza', 'taco'],
       ['taco', 'popcorn', 'popcorn', 'pizza']], dtype='<U7')

# Array Attributes

# 1. reshape()

In [18]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a2 = np.arange(12,dtype=float)
a2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [24]:
a2=a2.reshape(3,4)

In [23]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [26]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim

In [33]:
a1.ndim

1

In [34]:
# ndim
a2.ndim

1

In [35]:
a3.ndim

3

# shape

In [38]:
# shape
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1.shape

(10,)

In [40]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [41]:
a2.shape

(3, 4)

In [42]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a3.shape

(2, 2, 2)

# size

In [44]:
print(a1.size)

10


In [45]:
# size
print(a2.size)


12


In [46]:
print(a3.size)

8


# dtype()

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

### Array Operations

In [27]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Arithmetic Operations

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

In [ ]:
#+,-,/,*,**,//
a2//3

In [ ]:
a2

# Relational operators/Comparison operators

In [28]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
a2[a2<20]

array([12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
# relational operators-- <,>,<=,>=,==,!=
a2[a2 == 15]

array([15])

In [ ]:
a2[a2<15]

In [ ]:
# find out even numbers
a2[a2 % 2 == 0]

In [ ]:
# find all numbers not divisible by 7
a2[~(a2 % 7 == 0)]

In [ ]:
#filter out all the negative numbers

In [53]:
# Working with missing values -> np.nan
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [54]:
a[np.isnan(a)]

array([nan])

In [55]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])


# Logical Operators

In [31]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
np.logical_and(a2 > 13, a2<22)

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [33]:
a2[np.logical_and(a2 > 13, a2<22)]

array([14, 15, 16, 17, 18, 19, 20, 21])

In [34]:
np.logical_or(a2 > 15, a2>22)

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a2[np.logical_or(a2 > 15, a2>22)]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [36]:
np.logical_not(a2 > 19)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [ ]:
a2[np.logical_not(a2 > 19)]

# Vector Operations

In [ ]:
a1,a2

In [ ]:
# arithmetic
a1+a2

In [ ]:
a1*a2

In [ ]:
a1-a2

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1


In [ ]:
a1=a1*100
a1=np.round(a1)
a1

In [ ]:
a1=a1.astype(np.int64)

In [ ]:
a1

# prod()

In [59]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
np.prod(a1)

0

In [61]:
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([  0,  45, 120, 231])

In [63]:
np.prod(a1,axis=1)

array([   0,  840, 7920])

# Mean()

In [ ]:
np.mean(a1)

In [ ]:
np.mean(a1,axis=0)

In [ ]:
np.mean(a1,axis=1)

# max()

In [ ]:
a2

In [ ]:
np.max(a2)

In [ ]:
np.max(a2,axis=0)

In [ ]:
np.max(a2,axis=1)

# min()

In [ ]:
a2

In [ ]:
np.min(a2)

In [ ]:
np.min(a2,axis=0)

In [ ]:
np.min(a2,axis=1)

# sum()

In [ ]:
a2

In [ ]:
np.sum(a2)

In [ ]:
np.sum(a2,axis=0)

In [ ]:
np.sum(a2,axis=1)

# Median()

In [ ]:
np.median(a1)

In [ ]:
np.median(a1,axis=0)

In [ ]:
np.median(a1,axis=1)

# std()

In [ ]:
np.std(a1)

In [ ]:
np.std(a1,axis=0)

In [ ]:
np.std(a1,axis=1)

# Var()

In [ ]:
np.var(a1)

In [ ]:
np.var(a1,axis=0)

In [ ]:
np.var(a1,axis=1)

# trignometric functions

In [64]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [ ]:
np.cos(a1)

In [ ]:
np.tan(a1)

# Dot Product

In [66]:
# dot product
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a3 = np.arange(12,24).reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [68]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# log()

In [69]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.log(a1)

/tmp/ipykernel_284350/2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

# exp()

In [71]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# Round/floor/ceil

In [72]:
a1=np.random.random((2,3))
a1

array([[0.04216242, 0.63507904, 0.1839717 ],
       [0.90146563, 0.73359831, 0.19047046]])

In [73]:
a2=a1*100
a2

array([[ 4.2162417 , 63.50790444, 18.39717029],
       [90.14656251, 73.35983074, 19.04704592]])

In [74]:
np.floor(a2)

array([[ 4., 63., 18.],
       [90., 73., 19.]])

In [75]:
np.round(a2)

array([[ 4., 64., 18.],
       [90., 73., 19.]])

In [76]:
np.ceil(a2)

array([[ 5., 64., 19.],
       [91., 74., 20.]])

# Transpose()

In [77]:
a2

array([[ 4.2162417 , 63.50790444, 18.39717029],
       [90.14656251, 73.35983074, 19.04704592]])

In [78]:
np.transpose(a2)

array([[ 4.2162417 , 90.14656251],
       [63.50790444, 73.35983074],
       [18.39717029, 19.04704592]])

# ravel()

In [79]:
a2

array([[ 4.2162417 , 63.50790444, 18.39717029],
       [90.14656251, 73.35983074, 19.04704592]])

In [80]:
a2.ravel()

array([ 4.2162417 , 63.50790444, 18.39717029, 90.14656251, 73.35983074,
       19.04704592])

In [81]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [82]:
a3.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# Indexing and Slicing

In [83]:
a1 = np.random.random(10)
a2 = (np.arange(12).reshape(3,4))*2
a3 = (np.arange(8).reshape(2,2,2))*2
print(a1)
print("\n")
print(a2)
print("\n")
print(a3)

[0.08290056 0.83062753 0.23753605 0.50711795 0.53525103 0.96512238
 0.51635798 0.89709237 0.50438584 0.07750923]


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]


In [ ]:
a1

In [ ]:
a1[2]

In [ ]:
a1[3:7]

In [ ]:
a1[3:7:2]

In [ ]:
a2

In [ ]:
#a2[row,column]
a2[1,0]

In [ ]:
a2[1:,2]

In [ ]:
a2[1:,2:]

In [ ]:
a2[0:2,1::2]

In [ ]:
a2[::2,1::2]

In [ ]:
a2[1:,1:3]

In [ ]:
a3

In [ ]:
#a3[matrix,row,column]
a3[1,0,1]

In [ ]:
a3[1,1,0]

In [ ]:
a3[1,:,1]

In [ ]:
a3[0,1:,:]

In [ ]:
a3 = np.arange(27).reshape(3,3,3)*2
a3

In [ ]:
a3[:2,0,1:]

In [ ]:
a3[2,1:,1:]

In [ ]:
a3[0,1,:]

### Stacking

In [84]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1

array([1, 2, 3])

In [85]:
a2

array([4, 5, 6])

In [86]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [87]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [91]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [8]:
arr = np.array([1, 2, 3, 4, 5])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5])]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)
print(type(newarr))

[array([1, 2]), array([3, 4]), array([5]), array([6])]
<class 'list'>


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

In [ ]:
newarr

In [ ]:
newarr[0]

In [ ]:
newarr[0][1]

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

In [ ]:
newarr[0]

In [ ]:
newarr[1]

In [ ]:
newarr[2]

In [ ]:
newarr[0][1,1]

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)

print(newarr)

# Working with mathematical formulas

In [11]:
# sigmoid
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))


In [12]:
a = np.arange(100)

In [13]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [98]:
def mse(actual,predicted):
  return np.mean((actual - predicted)**2)


In [99]:
# mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [100]:
actual

array([35, 13,  3, 38, 29, 12, 20, 29,  2, 15, 27, 34, 39,  6, 41, 44, 24,
       11, 48, 36, 28, 10, 47, 34, 30])

In [101]:
predicted

array([29, 32, 41, 46, 28, 14, 39, 21,  4, 11,  3, 30, 32, 36, 35, 15, 27,
       20, 37, 49, 11, 24, 10, 20, 49])

In [102]:
mse(actual,predicted)

302.56